### ISSUE TITLE
Build Script for device drivers

### ISSUE THREAD

**Issue by gharris1727** [robotics-at-maryland/qubo#28]
The device drivers (most notably the AHRS and DVL) currently build into their local bin/ folders. They also have includes that are required by the other systems. All of this needs to be added the the build script/catkin/cmake/whatever.

**Comment by sgillen** [comment]
I integrated your stuff as a package (I know i said earlier I wanted them separately, but upon further reflection I realize I like it better as a package), please confirm everything still builds the way you want and that your binaries still work (should be able to run them via rosrun now, though if you want to raw binaries you can search through the devel folder). If you like the way the setup is then please remove the Makefiles
