### ISSUE TITLE
Error with vision when running catkin_make

### ISSUE THREAD

**Issue by hephaestus9** [robotics-at-maryland/qubo#39]
When running catkin_make I received the following error:

> -- Could not find the required component 'OpenCV'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
>CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
>  Could not find a package configuration file provided by "OpenCV" with any
>  of the following names:
>
>    OpenCVConfig.cmake
>    opencv-config.cmake
>
>  Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
>  "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
>  provides a separate development package or SDK, be sure it has been
>  installed.
>Call Stack (most recent call first):
>  vision/CMakeLists.txt:7 (find_package)
>
>
>-- Configuring incomplete, errors occurred!
>See also "/home/jeramy/Documents/RatM/qubo/build/CMakeFiles/CMakeOutput.log".
>See also "/home/jeramy/Documents/RatM/qubo/build/CMakeFiles/CMakeError.log".
>Invoking "cmake" failed

Installing opencv from apt did not fix it, so I installed it from source (http://docs.opencv.org/3.0-last-rst/doc/tutorials/introduction/linux_install/linux_install.html)

The error persisted, but I had seen that one of the commits in the vision folder was to take out a line that broke the install.

As per the install instructions this was my install location: CMAKE_INSTALL_PREFIX=/usr/local

So I uncommented the line in .../qubo/src/vision/CMakeList.txt from:
>#set(OpenCV_DIR /usr/share/OpenCV/)
to 
>set(OpenCV_DIR /usr/local/share/OpenCV/)

This corrected the error.

**Comment by sgillen** [comment]
let's keep setting that environment variable in the .bashrc. The reason is that the computer on the physical robot is using different version of OpenCV that lives somewhere else. I would actually advise you actually uninstall the version you built from source just so you're on the same page as the rest of the team (who is using openCV)
