### ISSUE TITLE
Error with ram_msgs when running catkin_make

### ISSUE THREAD

**Issue by hephaestus9** [robotics-at-maryland/qubo#40]
running catkin_make as per the readme results in the following error.

>[  5%] Building CXX object vision/CMakeFiles/canny_tuner.dir/src/canny_tuner.cpp.o
>[  5%] Building CXX object vl_qubo/CMakeFiles/qubo_dvl_node.dir/dvl/src/main.cpp.o
>[  5%] Building CXX object vision/CMakeFiles/gpu_vision_node.dir/src/gpu_main.cpp.o
>In file included from /home/jeramy/Documents/RatM/qubo/src/vl_qubo/dvl/src/main.cpp:1:0:
>/home/jeramy/Documents/RatM/qubo/src/vl_qubo/dvl/include/dvl_qubo.h:6:31: fatal error: >ram_msgs/DVL_qubo.h: No such file or directory
>compilation terminated.
>/home/jeramy/Documents/RatM/qubo/src/vision/src/canny_tuner.cpp: In function ‘int main(int, char**)’:
>/home/jeramy/Documents/RatM/qubo/src/vision/src/canny_tuner.cpp:66:31: warning: ISO C++ forbids >converting a string constant to ‘char*’ [-Wwrite-strings]
>         char* source_window = "Source";
>                              ^
>vl_qubo/CMakeFiles/qubo_dvl_node.dir/build.make:62: recipe for target 'vl_qubo/CMakeFiles/qubo_dvl_node.dir/dvl/src/main.cpp.o' failed
>make[2]: *** [vl_qubo/CMakeFiles/qubo_dvl_node.dir/dvl/src/main.cpp.o] Error 1
>CMakeFiles/Makefile2:4544: recipe for target 'vl_qubo/CMakeFiles/qubo_dvl_node.dir/all' failed
>make[1]: *** [vl_qubo/CMakeFiles/qubo_dvl_node.dir/all] Error 2
>make[1]: *** Waiting for unfinished jobs....
>[  6%] Building CXX object vision/CMakeFiles/gpu_vision_node.dir/src/gpu_vision_node.cpp.o
...
>Makefile:138: recipe for target 'all' failed
>make: *** [all] Error 2
>Invoking "make -j4 -l4" failed

deleting the build and devel folders and running:
`catkin_make ram_msgs
catkin_make ram_cpp_utils
catkin_make controls
catkin_make joystick
catkin_make vision
catkin_make vl_tortuga
catkin_make vl_qubo
catkin_make`

appears to result in a good build

**Comment by sgillen** [comment]
Pull the latest, delete your qubo/devel and qubo/build directories and try catkin make again. The error is caused because that DVL_qubo.h file is actually generated during the build, and it was not listed as a dependency, so the compiler looked for that file before it had been created.
